/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/safeDoor.glb -t
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Door_1: THREE.Mesh
    Door_2: THREE.Mesh
    Door_3: THREE.Mesh
    ButtonEight: THREE.Mesh
    ButtonFive: THREE.Mesh
    ButtonFour: THREE.Mesh
    ButtonHash: THREE.Mesh
    ButtonNine: THREE.Mesh
    ButtonOne: THREE.Mesh
    ButtonSeven: THREE.Mesh
    ButtonSix: THREE.Mesh
    ButtonStar: THREE.Mesh
    ButtonThree: THREE.Mesh
    ButtonTwo: THREE.Mesh
    ButtonZero: THREE.Mesh
    Lock: THREE.Mesh
    Screen: THREE.Mesh
  }
  materials: {}
}

export function SafeDoor(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/safeDoor.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Door_1.geometry} material={nodes.Door_1.material} />
      <mesh geometry={nodes.Door_2.geometry} material={nodes.Door_2.material} />
      <mesh geometry={nodes.Door_3.geometry} material={nodes.Door_3.material} />
      <mesh geometry={nodes.ButtonEight.geometry} material={nodes.ButtonEight.material} position={[-0.293, 0.03, 0.008]} />
      <mesh geometry={nodes.ButtonFive.geometry} material={nodes.ButtonFive.material} position={[-0.293, 0.058, 0.008]} />
      <mesh geometry={nodes.ButtonFour.geometry} material={nodes.ButtonFour.material} position={[-0.321, 0.058, 0.008]} />
      <mesh geometry={nodes.ButtonHash.geometry} material={nodes.ButtonHash.material} position={[-0.265, 0.002, 0.008]} />
      <mesh geometry={nodes.ButtonNine.geometry} material={nodes.ButtonNine.material} position={[-0.265, 0.03, 0.008]} />
      <mesh geometry={nodes.ButtonOne.geometry} material={nodes.ButtonOne.material} position={[-0.321, 0.086, 0.008]} />
      <mesh geometry={nodes.ButtonSeven.geometry} material={nodes.ButtonSeven.material} position={[-0.321, 0.03, 0.008]} />
      <mesh geometry={nodes.ButtonSix.geometry} material={nodes.ButtonSix.material} position={[-0.265, 0.058, 0.008]} />
      <mesh geometry={nodes.ButtonStar.geometry} material={nodes.ButtonStar.material} position={[-0.321, 0.002, 0.008]} />
      <mesh geometry={nodes.ButtonThree.geometry} material={nodes.ButtonThree.material} position={[-0.265, 0.086, 0.008]} />
      <mesh geometry={nodes.ButtonTwo.geometry} material={nodes.ButtonTwo.material} position={[-0.293, 0.086, 0.008]} />
      <mesh geometry={nodes.ButtonZero.geometry} material={nodes.ButtonZero.material} position={[-0.293, 0.002, 0.008]} />
      <mesh geometry={nodes.Lock.geometry} material={nodes.Lock.material} position={[-0.443, 0.061, 0.012]} />
      <mesh geometry={nodes.Screen.geometry} material={nodes.Screen.material} position={[-0.293, 0.116, 0.005]} />
    </group>
  )
}

useGLTF.preload('/safeDoor.glb')
